resources:
  - url: /local/mini-media-player/mini-media-player.js?v=0.8.9
    type: module
  - url: /local/custom-lovelace/monster-card/monster-card.js?v=1
    type: module
title: Sofia Home
views:
  - title: home
    icon: mdi:home
    cards:

      - type: entities
        title: Switches
        entities:
          - light.livingroomlight
          - light.living_room_light_2
          - switch.tv_backlight
          - switch.wake_on_lan
          - switch.pi_hole 
          - type: divider          
          - light.kitchen_main_light
          - switch.kitchen_light
          - type: divider
          - light.ivancho_room_light
          - type: divider
          - switch.bath_vent
      - type: vertical-stack
        cards:      
          - type: custom:mini-media-player
            entity: media_player.kitchen
            name: Kitchen Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
          - type: custom:mini-media-player
            entity: media_player.living_room
            name: Livingroom Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
          - type: custom:mini-media-player
            entity: media_player.ivanchoroom
            name: Ivancho Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true         
      - type: vertical-stack
        cards:  
          - type: glance
            show_name: false
            entities:
              - device_tracker.google_maps_108650450444917409685
              - sensor.tanya_battery
              - device_tracker.google_maps_118240125134652561295
              - sensor.hristo_battery
              - sensor.home_alarm
          - type: map
            aspect_ratio: 100%
            default_zoom: 14
            entities:
              - device_tracker.google_maps_118240125134652561295
              - device_tracker.google_maps_108650450444917409685
  - title: Home Temp
    icon: mdi:temperature-celsius
    cards:
      - type: entities
        title: Home Temperatures
        entities:
          - sensor.kitchen_temp
          - sensor.kitchen_hum
          - sensor.dewpoint
          - sensor.vent_kitchen
          - type: divider
          - sensor.livingroom_temperature
          - sensor.livingroom_humidity
          - type: divider
          - sensor.ivancho_room_temperature
          - sensor.ivan_room_humidity
          - type: divider
          - sensor.pws_temp_c
          - sensor.pws_relative_humidity
          - sensor.pws_dewpoint_c
      - type: history-graph
        title: 'Home Weather'
        entities:
          - sensor.kitchen_temp
          - sensor.kitchen_hum
          - sensor.dewpoint
          - sensor.vent_kitchen
          - sensor.livingroom_temperature
          - sensor.livingroom_humidity
          - sensor.ivancho_room_temperature
          - sensor.ivan_room_humidity
          - sensor.pws_temp_c
          - sensor.pws_relative_humidity
          - sensor.pws_dewpoint_c
  - title: Music
    icon: mdi:music
    cards:
      - type: entities
        title: Multy Room Audio
        entities:
          - input_select.radio_select
          - input_select.spotify_select
      - type: media-control
      
        entity: media_player.ivanchoroom
      - type: media-control
        entity: media_player.kitchen
      - type: media-control
        entity: media_player.living_room
      - type: media-control
        entity: media_player.mpclivingroom
      - type: picture-glance
        entity: camera.movie_poster
      - type: media-control
        entity: media_player.spotify
  - title: Cameras
    icon: mdi:webcam
    cards:
      - type: picture-glance
        entities:
          - light.livingroomlight
          - light.living_room_light_2
          - sensor.livingroom_temperature
          - sensor.livingroom_humidity
        camera_image: camera.camera_living_room
        title: Living Room
      - type: entities
        entities:
          - input_select.ivancho_cam
      - type: picture-glance
        entities:
          - light.ivancho_room_light
          - sensor.ivancho_room_temperature
          - sensor.ivan_room_humidity
        camera_image: camera.ivancho_camera
        title: Ivancho
      - type: picture-glance
        entities:
          - switch.kitchen_light
          - light.kitchen_main_light
          - sensor.kitchen_temp
          - sensor.kitchen_hum
        camera_image: camera.kitchen_cam
        title: Kitchen
      - type: picture-glance
        entities:
          - switch.wake_on_lan
        camera_image: camera.home_pc

  - title: My Devices
    icon: mdi:chip
    cards:
      - type: entities
        title: Home PC
        entities:
          - sensor.hpc_cpu_temp
          - sensor.hpc_cpu_usage
          - sensor.hpc_free_memory
          - sensor.hpc_used_memory
          - switch.wake_on_lan
      - type: picture-glance
        entity: camera.homepc
      - type: entities
        title: ARM CPU Temperatures
        entities:
          - sensor.rpi_1_cpu_temp
          - sensor.rpi3_cpu_temp
          - sensor.rpi0_ivancho_cpu_temp
          - sensor.rpi0_kitchen_cpu_temp
          - sensor.rpi2_cpu_temp
          - sensor.rpi0w_cpu_temp
      - type: entities
        title: ARM CPU Load
        entities:
          - sensor.rpi_1_cpu_load
          - sensor.rpi3_cpu_load
          - sensor.rpi0_ivancho_cpu
          - sensor.rpi0_kitchen_cpu
          - sensor.rpi2_cpu
          - sensor.rpi0w_cpu_load
      - type: entities
        title: ARM Disk Usage
        entities:
          - sensor.rpi_1_diskusage
          - sensor.rpi3_diskusage
          - sensor.rpi0_ivancho_diskusage
          - sensor.rpi0_kitchen_diskusage
          - sensor.rpi2_diskusage
          - sensor.rpi0w_diskusage
      # - type: entities
        # title: x86 Temperatures
        # entities:
          # - sensor.main_pc_cpu_load
          # - sensor.main_pc_cpu_temp
          # - sensor.main_pc_gpu_load
          # - sensor.main_pc_gpu_temp
          # - sensor.kitchen_pc_cpu_load
          # - sensor.kitchen_pc_cpu_temp
      - type: sensor
        entity: sensor.avrg__messages_per_1_min
        name: MQTT Stats
        height: 75
        line_color: "#3498db"     

  - title: Weather
    icon: mdi:cloud

    cards:

      - type: history-graph
        title: 'Sofia Weather'
        entities:
          - sensor.pws_temp_c
          - sensor.pws_relative_humidity
          - sensor.pws_dewpoint_c
      - type: iframe
        title: Air Quality Sofiq
        url: https://maps.luftdaten.info/#13/42.6748/23.3604
        aspect_ratio: 75%
      - type: entities
        title: Air Quality SF
        entities:
          - sensor.air_polution_sofia_pm10
          - sensor.air_polution_sofia_pm25
      - type: iframe
        title: Air Quality Stara Zagora
        url: https://maps.luftdaten.info/#13/42.4243/25.6344
        aspect_ratio: 75%
      - type: entities
        title: Air Quality Stara Zagora
        entities:
          - sensor.air_polution_sz_pm10
          - sensor.air_polution_sz_pm25
      - type: entities
        title: Weather overview
        entities:
          # - sensor.pws_weather_1d_metric
          - sensor.pws_temp_high_record_c
          - sensor.pws_temp_high_1d_c
          - sensor.pws_temp_c
          - sensor.pws_temp_low_1d_c
          - sensor.pws_temp_low_record_c
          - sensor.pws_precip_1d
          - sensor.pws_precip_1d_mm
          - sensor.pws_wind_kph
          - sensor.pws_wind_1d_kph
          - sensor.pws_alerts
      - type: glance
        title: Sun and moon
        show_name: true
        entities:
          - sun.sun
          - sensor.moon
  - title: Livingroom
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            entities:
              - switch.tv_backlight
              - light.livingroomlight
              - light.living_room_light_2
              - sensor.livingroom_temperature
              - sensor.livingroom_humidity
            camera_image: camera.camera_living_room
          - type: horizontal-stack
            cards:     
              - type: sensor
                entity: sensor.livingroom_temperature
                name: Livingroom Temperature
                height: 75
                line_color: red
              - type: sensor
                entity: sensor.livingroom_humidity
                name: Livingroom Humidity
                height: 75
                line_color: "#3498db"        
          - type: custom:mini-media-player
            entity: media_player.living_room
            name: Livingroom Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
          - type: entities
            title: Home PC
            entities:
              - sensor.hpc_cpu_temp
              - sensor.hpc_cpu_usage
              - sensor.hpc_free_memory
              - sensor.hpc_used_memory
              - switch.wake_on_lan

  - title: Ivancho Room
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            entities:
              - light.ivancho_room_light
              - sensor.ivancho_room_temperature
              - sensor.ivan_room_humidity
              - sensor.ivancho_room_motion
            camera_image: camera.ivancho_camera
          - type: entities
            entities:
              - input_select.ivancho_cam
          - type: horizontal-stack
            cards:     
              - type: sensor
                entity: sensor.ivancho_room_temperature
                name: Ivancho Room Temperature
                height: 75
                line_color: red
              - type: sensor
                entity: sensor.ivan_room_humidity
                name: Ivancho Room Humidity
                height: 75
                line_color: "#3498db"        
          - type: custom:mini-media-player
            entity: media_player.ivanchoroom
            name: Ivancho Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
          - type: entities
            entities:
              - switch.foscam_motion_ivanchoroom
              - sensor.ivancho_room_motion
              
  - title: Kitchen
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            entities:
              - switch.kitchen_light
              - light.kitchen_main_light
              - sensor.kitchen_temp
              - sensor.kitchen_hum
            camera_image: camera.kitchen_cam
          - type: horizontal-stack
            cards:     
              - type: sensor
                entity: sensor.kitchen_temp
                name: Kitchen Temperature
                height: 75
                line_color: red
              - type: sensor
                entity: sensor.kitchen_hum
                name: Kitchen Humidity
                height: 75
                line_color: "#3498db"        
          - type: custom:mini-media-player
            entity: media_player.kitchen
            name: Kitchen Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
  - title: All
    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            entities:
              - switch.tv_backlight
              - light.livingroomlight
              - light.living_room_light_2
              - sensor.livingroom_temperature
              - sensor.livingroom_humidity
            camera_image: camera.camera_living_room
          - type: horizontal-stack
            cards:     
              - type: sensor
                entity: sensor.livingroom_temperature
                name: Livingroom Temperature
                height: 75
                line_color: red
              - type: sensor
                entity: sensor.livingroom_humidity
                name: Livingroom Humidity
                height: 75
                line_color: "#3498db"        
          - type: custom:mini-media-player
            entity: media_player.living_room
            name: Livingroom Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
          - type: entities
            title: Home PC
            entities:
              - sensor.hpc_cpu_temp
              - sensor.hpc_cpu_usage
              - sensor.hpc_free_memory
              - sensor.hpc_used_memory
              - switch.wake_on_lan

#  - title: Ivancho Room
#    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            entities:
              - light.ivancho_room_light
              - sensor.ivancho_room_temperature
              - sensor.ivan_room_humidity
              - sensor.ivancho_room_motion
            camera_image: camera.ivancho_camera

          - type: horizontal-stack
            cards:     
              - type: sensor
                entity: sensor.ivancho_room_temperature
                name: Ivancho Room Temperature
                height: 75
                line_color: red
              - type: sensor
                entity: sensor.ivan_room_humidity
                name: Ivancho Room Humidity
                height: 75
                line_color: "#3498db"        
          - type: custom:mini-media-player
            entity: media_player.ivanchoroom
            name: Ivancho Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
          - type: entities
            entities:
              - input_select.ivancho_cam
          - type: entities
            entities:
              - switch.foscam_motion_ivanchoroom
              - sensor.ivancho_room_motion
              
#  - title: Kitchen
#    cards:
      - type: vertical-stack
        cards:
          - type: picture-glance
            entities:
              - switch.kitchen_light
              - light.kitchen_main_light
              - sensor.kitchen_temp
              - sensor.kitchen_hum
            camera_image: camera.kitchen_cam
          - type: horizontal-stack
            cards:     
              - type: sensor
                entity: sensor.kitchen_temp
                name: Kitchen Temperature
                height: 75
                line_color: red
              - type: sensor
                entity: sensor.kitchen_hum
                name: Kitchen Humidity
                height: 75
                line_color: "#3498db"        
          - type: custom:mini-media-player
            entity: media_player.kitchen
            name: Kitchen Player
            artwork: cover
            power_color: true
            hide_volume: false
            show_progress: true
  - title: All Entities
    icon: mdi:settings
    cards:
        - type: entity-filter
          entities:
              - light.kitchen_main_light
              - switch.tv_backlight
              - light.livingroomlight
              - light.living_room_light_2
              - light.ivancho_room_light
              - switch.wake_on_lan
              - switch.pi_hole
              - switch.kitchen_light
              - switch.bath_vent
          state_filter:
            - "unavailable"
